### ISSUE TITLE
How to filter to command run in local0 to 7 

### ISSUE THREAD

**Issue by liberodark** [slackhq/go-audit#111]
Hi,

I want to filter for juste see all commands running by users in local0 to 7

I think is here:  ?
```
# If kaudit filtering isn't powerful enough you can use the following filter mechanism
filters:
  # Each filter consists of exactly 3 parts
  - syscall: 54 # The syscall id of the message group (a single log line from go-audit), to test against the regex
    message_type: 1306 # The message type identifier containing the data to test against the regex
    regex: saddr=(10..|0A..) # The regex to test against the message specific message types data
```
 
Best Regards
